export const GET_INCIDENT = 'GET_INCIDENT';
export const GET_CONTACT = 'GET_CONTACT';
export const GET_INVOLVED = 'GET_INVOLVED';
export const GET_SUMMARY = 'GET_SUMMARY';
export const GET_PASSENGERS = 'GET_PASSENGERS'